-- Question 2
SELECT *
FROM SAKILA.ACTOR

SELECT *
FROM SAKILA.FILM

SELECT *
FROM SAKILA.CUSTOMER

-- Question 3
SELECT DISTINCT TITLE
FROM SAKILA.FILM

-- Question 4
SELECT DISTINCT LANGUAGE_ID
				, NAME
FROM SAKILA.LANGUAGE

-- Question 5.1
SELECT COUNT(DISTINCT STORE_ID) AS STORE_COUNT
FROM SAKILA.STORE

-- Question 5.2
SELECT COUNT(DISTINCT STAFF_ID) AS EMPLOYEE_COUNT
FROM SAKILA.STAFF

-- Question 5.3
SELECT DISTINCT FIRST_NAME AS EMPLOYEE_FIRST_NAME
FROM SAKILA.STAFF
